#pragma config(UserModel, "C:/Users/staff/Desktop/clawBot-master/Branch/src/plainClawBot.h")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "C:/Users/staff/Desktop/clawBot-master/Branch/src/Man/Headers/Control.h"


task main(){
	//Check in separate threads
	startTask(checkArm);
	startTask(checkClaw);
	startTask(leftMotor);
	startTask(checkRack);

	while(true)
		checkMoveR(vexRT[Ch2]);
}
