#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    ,               sensorLineFollower)
#pragma config(Sensor, in2,    ,               sensorLineFollower)
#pragma config(Sensor, in3,    ,               sensorLineFollower)
#pragma config(Sensor, in6,    ,               sensorGyro)
#pragma config(Sensor, dgtl1,  ,               sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  ,               sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  ,               sensorTouch)
#pragma config(Sensor, dgtl8,  ,               sensorSONAR_cm)
#pragma config(Sensor, dgtl11, ,               sensorQuadEncoder)
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           LMot,          tmotorVex393_HBridge, openLoop, reversed, driveLeft)
#pragma config(Motor,  port5,           clawMotA,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           clawMotB,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armMot,        tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_3)
#pragma config(Motor,  port10,          RMot,          tmotorVex393_HBridge, openLoop, driveRight)

